### ISSUE TITLE
cg.sh Memory管理炸妈

### ISSUE THREAD

**Issue by Axoford12** [Rubiginosu/FrozenDaemon#4]
[cg.sh ](https://github.com/Rubiginosu/FrozenDaemon/blob/master/daemon/cgroup/cg.sh)
内存限制部分，蜜汁问题，取得的DEBUG信息如下：
## 开服前
`axoford12@Axoford12:~$ cat /sys/fs/cgroup/memory/server1/memory.max_usage_in_bytes`<br />
`3033407488`<br />
## 开服前(重复测试) 
`axoford12@Axoford12:~$ cat /sys/fs/cgroup/memory/server1/memory.max_usage_in_bytes `<br />
`3033407488`<br />
## 服务器启动，参数：mem = 10
`axoford12@Axoford12:~$ cat /sys/fs/cgroup/memory/server1/memory.max_usage_in_bytes` <br />
`1340616704 ` <br />
## 服务器被 kill -9 杀死
`axoford12@Axoford12:~$ cat /sys/fs/cgroup/memory/server1/memory.max_usage_in_bytes `<br />
`1705119744`

**Comment by ghost** [comment]
怕是爆炸了

**Comment by Axoford12** [comment]
Emmm

**Comment by Axoford12** [comment]
不能限制内存就悲剧了

**Comment by Axoford12** [comment]
可能是系统兼容问题吧
